import { backendClient } from "@/sanity/lib/backendClient";
import { NextRequest } from "next/server";

export async function POST(request: NextRequest) {
    try {
        for (const product of products) {
            await backendClient.createOrReplace(product);
        }
        return new Response();
    } catch (error) {
        console.error("error while adding products", error);
    }
}
const products = [
    {
        _createdAt: "2025-05-02T14:48:09Z",
        _id: "4ff238f9-0e44-4ca7-9611-acf0a152bc64",
        _originalId: "4ff238f9-0e44-4ca7-9611-acf0a152bc64",
        _rev: "0eXuCLzlZROMt8M6TZnwoL",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:28Z",
        category: {
            _ref: "aaa6d06c-42d7-4d74-a035-a5ce7f75d5cd",
            _type: "reference",
        },
        description:
            "Official UFC Champion merchandise featuring premium quality materials and authentic branding",
        image: {
            _type: "image",
            asset: {
                _ref: "image-90f1a1dd20670e641855500dd88d800abb99d25e-1400x1400-jpg",
                _type: "reference",
            },
        },
        name: "UFC champion",
        price: 500,
        slug: {
            _type: "slug",
            current: "ufc-champion",
        },
        stock: 1,
    },
    {
        _createdAt: "2025-05-01T13:53:33Z",
        _id: "64b13810-67be-417a-81eb-701d46104bd5",
        _originalId: "64b13810-67be-417a-81eb-701d46104bd5",
        _rev: "ta4vCxLDTb3gnDB7nGX1kP",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:30Z",
        category: {
            _ref: "aaa6d06c-42d7-4d74-a035-a5ce7f75d5cd",
            _type: "reference",
        },
        description:
            "Classic black t-shirt made from 100% cotton, perfect for everyday wear",
        image: {
            _type: "image",
            asset: {
                _ref: "image-f51bb37cd899cf2a91efc6286dcb366b319d2962-512x512-png",
                _type: "reference",
            },
        },
        name: "Black Tshirt",
        price: 15,
        slug: {
            _type: "slug",
            current: "black-tshirt",
        },
        stock: 100,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-001",
        _originalId: "product-001",
        _rev: "0eXuCLzlZROMt8M6TZnxkP",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:31Z",
        category: {
            _ref: "category-001",
            _type: "reference",
        },
        description:
            "Comfortable and stylish casual t-shirt for men, perfect for everyday wear",
        imageUrl:
            "https://images.pexels.com/photos/9558600/pexels-photo-9558600.jpeg",
        name: "Men's Casual T-Shirt 1",
        price: 19.99,
        slug: {
            _type: "slug",
            current: "mens-casual-t-shirt-1",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-002",
        _originalId: "product-002",
        _rev: "mKqpFXcr0FhOVwpHKar2QG",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:25Z",
        category: {
            _ref: "category-002",
            _type: "reference",
        },
        description:
            "Elegant summer dress for women, made from lightweight and breathable fabric",
        imageUrl:
            "https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg",
        name: "Women's Summer Dress 20",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "womens-summer-dress-1",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-003",
        _originalId: "product-003",
        _rev: "0eXuCLzlZROMt8M6TZo0BN",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:26Z",
        category: {
            _ref: "category-003",
            _type: "reference",
        },
        description:
            "High-performance running sneakers with advanced cushioning and support",
        imageUrl:
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        name: "Men's Running Sneakers 1",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "mens-running-sneakers-1",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-004",
        _originalId: "product-004",
        _rev: "mKqpFXcr0FhOVwpHKar3BR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:27Z",
        category: {
            _ref: "category-004",
            _type: "reference",
        },
        description:
            "Stylish high heels for women, perfect for formal occasions",
        imageUrl:
            "https://images.pexels.com/photos/1478442/pexels-photo-1478442.jpeg",
        name: "Women's High Heels 1",
        price: 59.99,
        slug: {
            _type: "slug",
            current: "womens-high-heels-1",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-005",
        _originalId: "product-005",
        _rev: "0eXuCLzlZROMt8M6TZo1cP",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:28Z",
        category: {
            _ref: "category-005",
            _type: "reference",
        },
        description:
            "Latest smartphone with advanced features and high-performance camera",
        imageUrl:
            "https://images.unsplash.com/photo-1592890288564-76628a30a657",
        name: "Smartphone Pro 1",
        price: 499.99,
        slug: {
            _type: "slug",
            current: "smartphone-pro-1",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-006",
        _originalId: "product-006",
        _rev: "ta4vCxLDTb3gnDB7nGX7Qj",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:29Z",
        category: {
            _ref: "category-006",
            _type: "reference",
        },
        description:
            "Powerful kitchen blender with multiple speed settings and durable construction",
        imageUrl:
            "https://images.pexels.com/photos/596093/pexels-photo-596093.jpeg",
        name: "Kitchen Blender 1",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "kitchen-blender-1",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-007",
        _originalId: "product-007",
        _rev: "0eXuCLzlZROMt8M6TZo2cL",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:37Z",
        category: {
            _ref: "category-007",
            _type: "reference",
        },
        description:
            "Engaging mystery novel with unexpected plot twists and compelling characters",
        imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4ebf0c",
        name: "Mystery Novel 1",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "mystery-novel-1",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-008",
        _originalId: "product-008",
        _rev: "ta4vCxLDTb3gnDB7nGX9Pd",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:38Z",
        category: {
            _ref: "category-008",
            _type: "reference",
        },
        description:
            "Fun family board game perfect for game nights and gatherings",
        imageUrl:
            "https://images.pexels.com/photos/5418937/pexels-photo-5418937.jpeg",
        name: "Family Board Game 1",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "family-board-game-1",
        },
        stock: 45,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-009",
        _originalId: "product-009",
        _rev: "ta4vCxLDTb3gnDB7nGXBev",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:39Z",
        category: {
            _ref: "category-009",
            _type: "reference",
        },
        description:
            "Premium yoga mat with non-slip surface and comfortable thickness",
        imageUrl:
            "https://images.unsplash.com/photo-1506126279646-a697353d3166",
        name: "Yoga Mat 1",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "yoga-mat-1",
        },
        stock: 60,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-010",
        _originalId: "product-010",
        _rev: "ta4vCxLDTb3gnDB7nGXDJL",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:40Z",
        category: {
            _ref: "category-010",
            _type: "reference",
        },
        description:
            "Elegant gold necklace with classic design and premium finish",
        imageUrl:
            "https://images.pexels.com/photos/1453008/pexels-photo-1453008.jpeg",
        name: "Gold Necklace 1",
        price: 99.99,
        slug: {
            _type: "slug",
            current: "gold-necklace-1",
        },
        stock: 10,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-011",
        _originalId: "product-011",
        _rev: "ta4vCxLDTb3gnDB7nGXEtf",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:41Z",
        category: {
            _ref: "category-011",
            _type: "reference",
        },
        description: "Hydrating moisturizer cream for all skin types",
        imageUrl:
            "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg",
        name: "Moisturizer Cream 1",
        price: 34.99,
        slug: {
            _type: "slug",
            current: "moisturizer-cream-1",
        },
        stock: 55,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-012",
        _originalId: "product-012",
        _rev: "mKqpFXcr0FhOVwpHKarBfe",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:35Z",
        category: {
            _ref: "category-012",
            _type: "reference",
        },
        description: "Luxurious leather sofa with premium craftsmanship",
        imageUrl: "https://images.unsplash.com/photo-1550581190-9c027cffa4db",
        name: "Leather Sofa 1",
        price: 499.99,
        slug: {
            _type: "slug",
            current: "leather-sofa-1",
        },
        stock: 10,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-013",
        _originalId: "product-013",
        _rev: "ta4vCxLDTb3gnDB7nGXHTR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:36Z",
        category: {
            _ref: "category-013",
            _type: "reference",
        },
        description: "Beautiful wall art piece to enhance your home decor",
        imageUrl:
            "https://images.pexels.com/photos/298842/pexels-photo-298842.jpeg",
        name: "Wall Art 1",
        price: 59.99,
        slug: {
            _type: "slug",
            current: "wall-art-1",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-014",
        _originalId: "product-014",
        _rev: "ta4vCxLDTb3gnDB7nGXI8P",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:37Z",
        category: {
            _ref: "category-014",
            _type: "reference",
        },
        description: "Complete cookware set with durable construction",
        imageUrl:
            "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg",
        name: "Cookware Set 1",
        price: 129.99,
        slug: {
            _type: "slug",
            current: "cookware-set-1",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-015",
        _originalId: "drafts.product-015",
        _rev: "702fddd3-462c-4942-ba7b-c5719038fe04",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:39Z",
        category: {
            _ref: "category-015",
            _type: "reference",
        },
        description: "Comfortable pet bed for your furry friend",
        imageUrl:
            "https://images.pexels.com/photos/7318093/pexels-photo-7318093.jpeg",
        name: "Pet Bed 1",
        price: 44.99,
        slug: {
            _type: "slug",
            current: "pet-bed-1",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-016",
        _originalId: "product-016",
        _rev: "mKqpFXcr0FhOVwpHKaqSMm",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:21Z",
        category: {
            _ref: "category-016",
            _type: "reference",
        },
        description: "Spacious and durable camping tent for outdoor adventures",
        imageUrl:
            "https://images.unsplash.com/photo-1504851149312-7b075307cc89",
        name: "Camping Tent 1",
        price: 149.99,
        slug: {
            _type: "slug",
            current: "camping-tent-1",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-017",
        _originalId: "product-017",
        _rev: "0eXuCLzlZROMt8M6TZnIXZ",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:22Z",
        category: {
            _ref: "category-017",
            _type: "reference",
        },
        description:
            "Lightweight and maneuverable stroller with safety features",
        imageUrl:
            "https://images.pexels.com/photos/3979330/pexels-photo-3979330.jpeg",
        name: "Baby Stroller 1",
        price: 199.99,
        slug: {
            _type: "slug",
            current: "baby-stroller-1",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-018",
        _originalId: "product-018",
        _rev: "0eXuCLzlZROMt8M6TZnIn3",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:23Z",
        category: {
            _ref: "category-018",
            _type: "reference",
        },
        description: "Advanced fitness tracker with heart rate monitoring",
        imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
        name: "Fitness Tracker 1",
        price: 69.99,
        slug: {
            _type: "slug",
            current: "fitness-tracker-1",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-019",
        _originalId: "product-019",
        _rev: "0eXuCLzlZROMt8M6TZnJI1",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:24Z",
        category: {
            _ref: "category-019",
            _type: "reference",
        },
        description: "Premium quality notebooks with smooth paper",
        imageUrl:
            "https://images.pexels.com/photos/590516/pexels-photo-590516.jpeg",
        name: "Notebook Set 1",
        price: 14.99,
        slug: {
            _type: "slug",
            current: "notebook-set-1",
        },
        stock: 60,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-020",
        _originalId: "product-020",
        _rev: "0eXuCLzlZROMt8M6TZnJmz",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:25Z",
        category: {
            _ref: "category-020",
            _type: "reference",
        },
        description: "Durable backpack with multiple compartments",
        imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
        name: "Travel Backpack 1",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "travel-backpack-1",
        },
        stock: 45,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-021",
        _originalId: "product-021",
        _rev: "ta4vCxLDTb3gnDB7nGWchj",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:26Z",
        category: {
            _ref: "category-001",
            _type: "reference",
        },
        description: "Classic polo shirt in breathable cotton",
        imageUrl:
            "https://images.pexels.com/photos/3760854/pexels-photo-3760854.jpeg",
        name: "Men's Polo Shirt 2",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "mens-polo-shirt-2",
        },
        stock: 45,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-022",
        _originalId: "product-022",
        _rev: "ta4vCxLDTb3gnDB7nGWcy7",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:27Z",
        category: {
            _ref: "category-002",
            _type: "reference",
        },
        description: "Elegant blouse with delicate details",
        imageUrl:
            "https://images.pexels.com/photos/1851350/pexels-photo-1851350.jpeg",
        name: "Women's Blouse 2",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "womens-blouse-2",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-023",
        _originalId: "product-023",
        _rev: "0eXuCLzlZROMt8M6TZnKqn",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:28Z",
        category: {
            _ref: "category-003",
            _type: "reference",
        },
        description: "Comfortable sneakers with cushioned insoles",
        imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        name: "Men's Casual Sneakers 2",
        price: 69.99,
        slug: {
            _type: "slug",
            current: "mens-casual-sneakers-2",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-024",
        _originalId: "product-024",
        _rev: "mKqpFXcr0FhOVwpHKaqVLr",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:29Z",
        category: {
            _ref: "category-004",
            _type: "reference",
        },
        description: "Stylish sandals with comfortable straps",
        imageUrl:
            "https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg",
        name: "Women's Sandals 2",
        price: 44.99,
        slug: {
            _type: "slug",
            current: "womens-sandals-2",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-025",
        _originalId: "product-025",
        _rev: "mKqpFXcr0FhOVwpHKaqVsW",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:30Z",
        category: {
            _ref: "category-005",
            _type: "reference",
        },
        description: "Feature-rich smartwatch with health tracking",
        imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12",
        name: "Smartwatch 1",
        price: 199.99,
        slug: {
            _type: "slug",
            current: "smartwatch-1",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-026",
        _originalId: "product-026",
        _rev: "mKqpFXcr0FhOVwpHKaqXHc",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:31Z",
        category: {
            _ref: "category-006",
            _type: "reference",
        },
        description:
            "Powerful vacuum cleaner with HEPA filter and multiple attachments",
        imageUrl:
            "https://images.pexels.com/photos/3839047/pexels-photo-3839047.jpeg",
        name: "Vacuum Cleaner 1",
        price: 149.99,
        slug: {
            _type: "slug",
            current: "vacuum-cleaner-1",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-027",
        _originalId: "product-027",
        _rev: "mKqpFXcr0FhOVwpHKaqYA3",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:32Z",
        category: {
            _ref: "category-007",
            _type: "reference",
        },
        description: "Epic fantasy novel with magical creatures and adventure",
        imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e",
        name: "Fantasy Novel 2",
        price: 34.99,
        slug: {
            _type: "slug",
            current: "fantasy-novel-2",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-028",
        _originalId: "product-028",
        _rev: "mKqpFXcr0FhOVwpHKaqYvE",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:33Z",
        category: {
            _ref: "category-008",
            _type: "reference",
        },
        description: "Challenging puzzle game with 1000 pieces",
        imageUrl:
            "https://images.pexels.com/photos/2907502/pexels-photo-2907502.jpeg",
        name: "Puzzle Game 2",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "puzzle-game-2",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-029",
        _originalId: "product-029",
        _rev: "ta4vCxLDTb3gnDB7nGWmU3",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:34Z",
        category: {
            _ref: "category-009",
            _type: "reference",
        },
        description: "Set of 4 neoprene-coated dumbbells for strength training",
        imageUrl:
            "https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg",
        name: "Dumbbell Set 2",
        price: 59.99,
        slug: {
            _type: "slug",
            current: "dumbbell-set-2",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-030",
        _originalId: "product-030",
        _rev: "ta4vCxLDTb3gnDB7nGWmgL",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:35Z",
        category: {
            _ref: "category-010",
            _type: "reference",
        },
        description: "Elegant sterling silver earrings with crystal accents",
        imageUrl:
            "https://images.pexels.com/photos/1454122/pexels-photo-1454122.jpeg",
        name: "Silver Earrings 2",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "silver-earrings-2",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-031",
        _originalId: "product-031",
        _rev: "mKqpFXcr0FhOVwpHKaqe4a",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:36Z",
        category: {
            _ref: "category-011",
            _type: "reference",
        },
        description: "Set of 6 long-lasting matte lipsticks in various shades",
        imageUrl:
            "https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg",
        name: "Lipstick Set 2",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "lipstick-set-2",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-032",
        _originalId: "product-032",
        _rev: "0eXuCLzlZROMt8M6TZnca9",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:37Z",
        category: {
            _ref: "category-012",
            _type: "reference",
        },
        description: "Modern wooden coffee table with storage space",
        imageUrl:
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        name: "Coffee Table 2",
        price: 299.99,
        slug: {
            _type: "slug",
            current: "coffee-table-2",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-033",
        _originalId: "product-033",
        _rev: "mKqpFXcr0FhOVwpHKaqnJy",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:38Z",
        category: {
            _ref: "category-013",
            _type: "reference",
        },
        description: "Contemporary wall clock with silent movement",
        imageUrl:
            "https://images.pexels.com/photos/2781814/pexels-photo-2781814.jpeg",
        name: "Wall Clock 2",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "wall-clock-2",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-034",
        _originalId: "product-034",
        _rev: "0eXuCLzlZROMt8M6TZng13",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:39Z",
        category: {
            _ref: "category-014",
            _type: "reference",
        },
        description: "Professional knife set with wooden block and sharpener",
        imageUrl:
            "https://images.pexels.com/photos/62276/pexels-photo-62276.jpeg",
        name: "Knife Set 2",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "knife-set-2",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-035",
        _originalId: "product-035",
        _rev: "0eXuCLzlZROMt8M6TZnh8j",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:40Z",
        category: {
            _ref: "category-015",
            _type: "reference",
        },
        description: "Interactive chew toy for dogs with squeaker",
        imageUrl:
            "https://images.pexels.com/photos/3361732/pexels-photo-3361732.jpeg",
        name: "Pet Toy 2",
        price: 19.99,
        slug: {
            _type: "slug",
            current: "pet-toy-2",
        },
        stock: 60,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-036",
        _originalId: "product-036",
        _rev: "mKqpFXcr0FhOVwpHKaqrTd",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:08Z",
        category: {
            _ref: "category-016",
            _type: "reference",
        },
        description:
            "Durable hiking backpack with multiple compartments and water bottle holders",
        imageUrl:
            "https://images.unsplash.com/photo-1527010154944-f2241763d806",
        name: "Hiking Backpack 2",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "hiking-backpack-2",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-037",
        _originalId: "product-037",
        _rev: "ta4vCxLDTb3gnDB7nGWrVP",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:10Z",
        category: {
            _ref: "category-017",
            _type: "reference",
        },
        description: "Digital baby monitor with night vision and two-way audio",
        imageUrl:
            "https://images.pexels.com/photos/1595391/pexels-photo-1595391.jpeg",
        name: "Baby Monitor 2",
        price: 129.99,
        slug: {
            _type: "slug",
            current: "baby-monitor-2",
        },
        stock: 18,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-038",
        _originalId: "product-038",
        _rev: "mKqpFXcr0FhOVwpHKaqtsQ",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:11Z",
        category: {
            _ref: "category-018",
            _type: "reference",
        },
        description: "Eco-friendly cork yoga block for stability and support",
        imageUrl:
            "https://images.pexels.com/photos/3825432/pexels-photo-3825432.jpeg",
        name: "Yoga Block 2",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "yoga-block-2",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-039",
        _originalId: "product-039",
        _rev: "0eXuCLzlZROMt8M6TZnnwf",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:12Z",
        category: {
            _ref: "category-019",
            _type: "reference",
        },
        description: "Premium fountain pen set with ink cartridges",
        imageUrl:
            "https://images.pexels.com/photos/261895/pexels-photo-261895.jpeg",
        name: "Pen Set 2",
        price: 9.99,
        slug: {
            _type: "slug",
            current: "pen-set-2",
        },
        stock: 70,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-040",
        _originalId: "product-040",
        _rev: "0eXuCLzlZROMt8M6TZnpVR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:12Z",
        category: {
            _ref: "category-020",
            _type: "reference",
        },
        description: "Genuine leather belt with classic buckle",
        imageUrl:
            "https://images.pexels.com/photos/1456706/pexels-photo-1456706.jpeg",
        name: "Leather Belt 2",
        price: 34.99,
        slug: {
            _type: "slug",
            current: "leather-belt-2",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-041",
        _originalId: "product-041",
        _rev: "0eXuCLzlZROMt8M6TZnqRV",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:14Z",
        category: {
            _ref: "category-001",
            _type: "reference",
        },
        description: "Waterproof winter jacket with thermal lining",
        imageUrl:
            "https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg",
        name: "Men's Jacket 3",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "mens-jacket-3",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-042",
        _originalId: "product-042",
        _rev: "0eXuCLzlZROMt8M6TZnrZB",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:14Z",
        category: {
            _ref: "category-002",
            _type: "reference",
        },
        description: "Floral print maxi skirt with elastic waistband",
        imageUrl:
            "https://images.pexels.com/photos/1034859/pexels-photo-1034859.jpeg",
        name: "Women's Maxi Skirt 3",
        price: 59.99,
        slug: {
            _type: "slug",
            current: "womens-maxi-skirt-3",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-043",
        _originalId: "product-043",
        _rev: "mKqpFXcr0FhOVwpHKaqvgv",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:15Z",
        category: {
            _ref: "category-003",
            _type: "reference",
        },
        description: "Classic leather loafers with cushioned insoles",
        imageUrl:
            "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg",
        name: "Men's Loafers 3",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "mens-loafers-3",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-044",
        _originalId: "product-044",
        _rev: "mKqpFXcr0FhOVwpHKaqvz4",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:16Z",
        category: {
            _ref: "category-004",
            _type: "reference",
        },
        description: "Leather ankle boots with block heel",
        imageUrl:
            "https://images.pexels.com/photos/1356207/pexels-photo-1356207.jpeg",
        name: "Women's Ankle Boots 3",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "womens-ankle-boots-3",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-045",
        _originalId: "product-045",
        _rev: "ta4vCxLDTb3gnDB7nGWzdJ",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:17Z",
        category: {
            _ref: "category-005",
            _type: "reference",
        },
        description:
            "High-performance tablet with retina display and long battery life",
        imageUrl:
            "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        name: "Tablet Pro 1",
        price: 399.99,
        slug: {
            _type: "slug",
            current: "tablet-pro-1",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-046",
        _originalId: "product-046",
        _rev: "mKqpFXcr0FhOVwpHKaqwkF",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:18Z",
        category: {
            _ref: "category-006",
            _type: "reference",
        },
        description: "Programmable coffee maker with thermal carafe",
        imageUrl:
            "https://images.pexels.com/photos/127846/pexels-photo-127846.jpeg",
        name: "Coffee Maker 1",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "coffee-maker-1",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-047",
        _originalId: "product-047",
        _rev: "mKqpFXcr0FhOVwpHKaqxyS",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:19Z",
        category: {
            _ref: "category-007",
            _type: "reference",
        },
        description: "Compelling biography of a historical figure",
        imageUrl:
            "https://images.unsplash.com/photo-1512820790803-83ca734da794",
        name: "Biography Book 3",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "biography-book-3",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-048",
        _originalId: "product-048",
        _rev: "ta4vCxLDTb3gnDB7nGX0kx",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:21Z",
        category: {
            _ref: "category-008",
            _type: "reference",
        },
        description: "Colorful building blocks for creative play",
        imageUrl:
            "https://images.pexels.com/photos/1632790/pexels-photo-1632790.jpeg",
        name: "Building Blocks 3",
        price: 34.99,
        slug: {
            _type: "slug",
            current: "building-blocks-3",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-049",
        _originalId: "product-049",
        _rev: "mKqpFXcr0FhOVwpHKaqzmx",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:22Z",
        category: {
            _ref: "category-009",
            _type: "reference",
        },
        description: "Professional tennis racket with comfortable grip",
        imageUrl:
            "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
        name: "Tennis Racket 3",
        price: 69.99,
        slug: {
            _type: "slug",
            current: "tennis-racket-3",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-050",
        _originalId: "product-050",
        _rev: "0eXuCLzlZROMt8M6TZnxgX",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:57Z",
        category: {
            _ref: "category-010",
            _type: "reference",
        },
        description: "Elegant pearl necklace with sterling silver clasp",
        imageUrl:
            "https://images.pexels.com/photos/2785565/pexels-photo-2785565.jpeg",
        name: "Pearl Necklace 3",
        price: 129.99,
        slug: {
            _type: "slug",
            current: "pearl-necklace-3",
        },
        stock: 10,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-051",
        _originalId: "product-051",
        _rev: "ta4vCxLDTb3gnDB7nGX30F",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:58Z",
        category: {
            _ref: "category-011",
            _type: "reference",
        },
        description:
            "Complete skincare set with cleanser, toner, and moisturizer",
        imageUrl:
            "https://images.pexels.com/photos/3685530/pexels-photo-3685530.jpeg",
        name: "Skincare Set 3",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "skincare-set-3",
        },
        stock: 45,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-052",
        _originalId: "product-052",
        _rev: "ta4vCxLDTb3gnDB7nGX3Op",
        _type: "product",
        _updatedAt: "2025-05-20T05:59:59Z",
        category: {
            _ref: "category-012",
            _type: "reference",
        },
        description: "Solid wood bookshelf with adjustable shelves",
        imageUrl:
            "https://images.unsplash.com/photo-1592495991535-8c15e5f0e6db",
        name: "Bookshelf 3",
        price: 249.99,
        slug: {
            _type: "slug",
            current: "bookshelf-3",
        },
        stock: 12,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-053",
        _originalId: "product-053",
        _rev: "0eXuCLzlZROMt8M6TZo0zh",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:00Z",
        category: {
            _ref: "category-013",
            _type: "reference",
        },
        description: "Handcrafted ceramic vase with modern design",
        imageUrl:
            "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg",
        name: "Decorative Vase 3",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "decorative-vase-3",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-054",
        _originalId: "product-054",
        _rev: "mKqpFXcr0FhOVwpHKar3MK",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:01Z",
        category: {
            _ref: "category-014",
            _type: "reference",
        },
        description: "Set of nesting mixing bowls with non-slip bases",
        imageUrl:
            "https://images.pexels.com/photos/3991976/pexels-photo-3991976.jpeg",
        name: "Mixing Bowl Set 3",
        price: 59.99,
        slug: {
            _type: "slug",
            current: "mixing-bowl-set-3",
        },
        stock: 28,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-055",
        _originalId: "product-055",
        _rev: "mKqpFXcr0FhOVwpHKar3XD",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:02Z",
        category: {
            _ref: "category-015",
            _type: "reference",
        },
        description:
            "Comfortable and durable pet collar with adjustable buckle",
        imageUrl:
            "https://images.pexels.com/photos/1367067/pexels-photo-1367067.jpeg",
        name: "Pet Collar 3",
        price: 14.99,
        slug: {
            _type: "slug",
            current: "pet-collar-3",
        },
        stock: 55,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-056",
        _originalId: "product-056",
        _rev: "ta4vCxLDTb3gnDB7nGX8M5",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:03Z",
        category: {
            _ref: "category-016",
            _type: "reference",
        },
        description: "Lightweight and warm sleeping bag for outdoor adventures",
        imageUrl:
            "https://images.unsplash.com/photo-1518609878373-06d740f60d8b",
        name: "Sleeping Bag 3",
        price: 69.99,
        slug: {
            _type: "slug",
            current: "sleeping-bag-3",
        },
        stock: 22,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-057",
        _originalId: "product-057",
        _rev: "mKqpFXcr0FhOVwpHKar53Z",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:05Z",
        category: {
            _ref: "category-017",
            _type: "reference",
        },
        description:
            "Safe and sturdy baby crib with adjustable mattress height",
        imageUrl:
            "https://images.pexels.com/photos/1439529/pexels-photo-1439529.jpeg",
        name: "Baby Crib 3",
        price: 249.99,
        slug: {
            _type: "slug",
            current: "baby-crib-3",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-058",
        _originalId: "product-058",
        _rev: "mKqpFXcr0FhOVwpHKar8np",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:07Z",
        category: {
            _ref: "category-018",
            _type: "reference",
        },
        description: "Essential daily vitamins for overall health and wellness",
        imageUrl:
            "https://images.pexels.com/photos/459688/pexels-photo-459688.jpeg",
        name: "Vitamin Supplement 3",
        price: 19.99,
        slug: {
            _type: "slug",
            current: "vitamin-supplement-3",
        },
        stock: 60,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-059",
        _originalId: "product-059",
        _rev: "ta4vCxLDTb3gnDB7nGXDNR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:08Z",
        category: {
            _ref: "category-019",
            _type: "reference",
        },
        description:
            "Organize your schedule with this stylish and functional planner",
        imageUrl:
            "https://images.pexels.com/photos/1366944/pexels-photo-1366944.jpeg",
        name: "Planner 3",
        price: 19.99,
        slug: {
            _type: "slug",
            current: "planner-3",
        },
        stock: 65,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-060",
        _originalId: "product-060",
        _rev: "ta4vCxLDTb3gnDB7nGXElT",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:10Z",
        category: {
            _ref: "category-020",
            _type: "reference",
        },
        description:
            "Stylish sunglasses with UV protection and polarized lenses",
        imageUrl:
            "https://images.pexels.com/photos/343720/pexels-photo-343720.jpeg",
        name: "Sunglasses 3",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "sunglasses-3",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-061",
        _originalId: "product-061",
        _rev: "ta4vCxLDTb3gnDB7nGXGkN",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:11Z",
        category: {
            _ref: "category-001",
            _type: "reference",
        },
        description: "Comfortable and breathable men's shorts for casual wear",
        imageUrl:
            "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg",
        name: "Men's Shorts 4",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "mens-shorts-4",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-062",
        _originalId: "product-062",
        _rev: "ta4vCxLDTb3gnDB7nGXHXX",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:12Z",
        category: {
            _ref: "category-002",
            _type: "reference",
        },
        description: "Soft and cozy women's cardigan for layering",
        imageUrl:
            "https://images.pexels.com/photos/974911/pexels-photo-974911.jpeg",
        name: "Women's Cardigan 4",
        price: 54.99,
        slug: {
            _type: "slug",
            current: "womens-cardigan-4",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-063",
        _originalId: "product-063",
        _rev: "ta4vCxLDTb3gnDB7nGXI0D",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:12Z",
        category: {
            _ref: "category-003",
            _type: "reference",
        },
        description: "Comfortable and durable men's sandals for summer",
        imageUrl:
            "https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg",
        name: "Men's Sandals 4",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "mens-sandals-4",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-064",
        _originalId: "product-064",
        _rev: "0eXuCLzlZROMt8M6TZo6vR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:14Z",
        category: {
            _ref: "category-004",
            _type: "reference",
        },
        description:
            "Stylish and comfortable women's sneakers for everyday wear",
        imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
        name: "Women's Sneakers 4",
        price: 69.99,
        slug: {
            _type: "slug",
            current: "womens-sneakers-4",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-065",
        _originalId: "product-065",
        _rev: "ta4vCxLDTb3gnDB7nGXJ7r",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:15Z",
        category: {
            _ref: "category-005",
            _type: "reference",
        },
        description:
            "Powerful 15-inch laptop with high-performance specifications",
        imageUrl:
            "https://images.unsplash.com/photo-1496181133206-80ce9b88a0a6",
        name: "Laptop 15-Inch 1",
        price: 799.99,
        slug: {
            _type: "slug",
            current: "laptop-15-inch-1",
        },
        stock: 10,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-066",
        _originalId: "product-066",
        _rev: "mKqpFXcr0FhOVwpHKaqvvR",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:16Z",
        category: {
            _ref: "category-006",
            _type: "reference",
        },
        description: "Versatile air fryer for healthy and delicious cooking",
        imageUrl:
            "https://images.pexels.com/photos/4397907/pexels-photo-4397907.jpeg",
        name: "Air Fryer 1",
        price: 99.99,
        slug: {
            _type: "slug",
            current: "air-fryer-1",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-067",
        _originalId: "product-067",
        _rev: "mKqpFXcr0FhOVwpHKaqwcz",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:17Z",
        category: {
            _ref: "category-007",
            _type: "reference",
        },
        description: "Comprehensive history book covering major world events",
        imageUrl:
            "https://images.unsplash.com/photo-1509023464722-18d996393ca8",
        name: "History Book 4",
        price: 44.99,
        slug: {
            _type: "slug",
            current: "history-book-4",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-068",
        _originalId: "product-068",
        _rev: "0eXuCLzlZROMt8M6TZnvBh",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:18Z",
        category: {
            _ref: "category-008",
            _type: "reference",
        },
        description:
            "Detailed action figure with multiple points of articulation",
        imageUrl:
            "https://images.pexels.com/photos/1632790/pexels-photo-1632790.jpeg",
        name: "Action Figure 4",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "action-figure-4",
        },
        stock: 45,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-069",
        _originalId: "product-069",
        _rev: "mKqpFXcr0FhOVwpHKaqxup",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:19Z",
        category: {
            _ref: "category-009",
            _type: "reference",
        },
        description: "Professional-grade soccer ball for training and matches",
        imageUrl:
            "https://images.pexels.com/photos/47730/pexels-photo-47730.jpeg",
        name: "Soccer Ball 4",
        price: 34.99,
        slug: {
            _type: "slug",
            current: "soccer-ball-4",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-070",
        _originalId: "product-070",
        _rev: "mKqpFXcr0FhOVwpHKaqz5P",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:21Z",
        category: {
            _ref: "category-010",
            _type: "reference",
        },
        description:
            "Elegant bracelet set with matching pieces for any occasion",
        imageUrl:
            "https://images.pexels.com/photos/1454121/pexels-photo-1454121.jpeg",
        name: "Bracelet Set 4",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "bracelet-set-4",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-071",
        _originalId: "product-071",
        _rev: "ta4vCxLDTb3gnDB7nGX1Pv",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:22Z",
        category: {
            _ref: "category-011",
            _type: "reference",
        },
        description:
            "Complete haircare set with shampoo, conditioner, and styling products",
        imageUrl:
            "https://images.pexels.com/photos/3739348/pexels-photo-3739348.jpeg",
        name: "Haircare Set 4",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "haircare-set-4",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-072",
        _originalId: "product-072",
        _rev: "ta4vCxLDTb3gnDB7nGX1sb",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:23Z",
        category: {
            _ref: "category-012",
            _type: "reference",
        },
        description: "Sturdy dining table perfect for family gatherings",
        imageUrl:
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
        name: "Dining Table 4",
        price: 399.99,
        slug: {
            _type: "slug",
            current: "dining-table-4",
        },
        stock: 10,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-073",
        _originalId: "product-073",
        _rev: "mKqpFXcr0FhOVwpHKar2Md",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:25Z",
        category: {
            _ref: "category-013",
            _type: "reference",
        },
        description: "Soft and decorative throw pillow for your living space",
        imageUrl:
            "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg",
        name: "Throw Pillow 4",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "throw-pillow-4",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-074",
        _originalId: "product-074",
        _rev: "ta4vCxLDTb3gnDB7nGX3X1",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:26Z",
        category: {
            _ref: "category-014",
            _type: "reference",
        },
        description: "Durable wooden cutting board for food preparation",
        imageUrl:
            "https://images.pexels.com/photos/3991976/pexels-photo-3991976.jpeg",
        name: "Cutting Board 4",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "cutting-board-4",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-075",
        _originalId: "product-075",
        _rev: "ta4vCxLDTb3gnDB7nGX3fD",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:27Z",
        category: {
            _ref: "category-015",
            _type: "reference",
        },
        description: "Comfortable and secure leash for your pet",
        imageUrl:
            "https://images.pexels.com/photos/1367067/pexels-photo-1367067.jpeg",
        name: "Pet Leash 4",
        price: 19.99,
        slug: {
            _type: "slug",
            current: "pet-leash-4",
        },
        stock: 60,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-076",
        _originalId: "product-076",
        _rev: "0eXuCLzlZROMt8M6TZo1gH",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:28Z",
        category: {
            _ref: "category-016",
            _type: "reference",
        },
        description:
            "Portable and comfortable camping chair for outdoor adventures",
        imageUrl:
            "https://images.unsplash.com/photo-1505843513577-22bb7d21e455",
        name: "Camping Chair 4",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "camping-chair-4",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-077",
        _originalId: "product-077",
        _rev: "ta4vCxLDTb3gnDB7nGX7Up",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:29Z",
        category: {
            _ref: "category-017",
            _type: "reference",
        },
        description: "Spacious and organized diaper bag for parents on the go",
        imageUrl:
            "https://images.pexels.com/photos/3979330/pexels-photo-3979330.jpeg",
        name: "Diaper Bag 4",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "diaper-bag-4",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-078",
        _originalId: "product-078",
        _rev: "ta4vCxLDTb3gnDB7nGX8Hz",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:30Z",
        category: {
            _ref: "category-018",
            _type: "reference",
        },
        description:
            "High-quality protein powder for muscle recovery and growth",
        imageUrl:
            "https://images.pexels.com/photos/416999/pexels-photo-416999.jpeg",
        name: "Protein Powder 4",
        price: 39.99,
        slug: {
            _type: "slug",
            current: "protein-powder-4",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-079",
        _originalId: "product-079",
        _rev: "ta4vCxLDTb3gnDB7nGX9bv",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:31Z",
        category: {
            _ref: "category-019",
            _type: "reference",
        },
        description: "Efficient desk organizer to keep your workspace tidy",
        imageUrl:
            "https://images.pexels.com/photos/590516/pexels-photo-590516.jpeg",
        name: "Desk Organizer 4",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "desk-organizer-4",
        },
        stock: 55,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-080",
        _originalId: "product-080",
        _rev: "mKqpFXcr0FhOVwpHKar8rS",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:32Z",
        category: {
            _ref: "category-020",
            _type: "reference",
        },
        description:
            "Stylish leather wallet with multiple card slots and coin pocket",
        imageUrl:
            "https://images.pexels.com/photos/1456706/pexels-photo-1456706.jpeg",
        name: "Wallet 4",
        price: 44.99,
        slug: {
            _type: "slug",
            current: "wallet-4",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-081",
        _originalId: "product-081",
        _rev: "ta4vCxLDTb3gnDB7nGXDFF",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:33Z",
        category: {
            _ref: "category-001",
            _type: "reference",
        },
        description: "Classic tailored suit perfect for formal occasions",
        imageUrl:
            "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
        name: "Men's Suit 5",
        price: 199.99,
        slug: {
            _type: "slug",
            current: "mens-suit-5",
        },
        stock: 15,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-082",
        _originalId: "product-082",
        _rev: "mKqpFXcr0FhOVwpHKarB5M",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:34Z",
        category: {
            _ref: "category-002",
            _type: "reference",
        },
        description: "Stylish and warm winter jacket with multiple pockets",
        imageUrl:
            "https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg",
        name: "Women's Jacket 5",
        price: 89.99,
        slug: {
            _type: "slug",
            current: "womens-jacket-5",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-083",
        _originalId: "product-083",
        _rev: "mKqpFXcr0FhOVwpHKarBc1",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:35Z",
        category: {
            _ref: "category-003",
            _type: "reference",
        },
        description: "Premium leather dress shoes with comfortable fit",
        imageUrl:
            "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg",
        name: "Men's Dress Shoes 5",
        price: 119.99,
        slug: {
            _type: "slug",
            current: "mens-dress-shoes-5",
        },
        stock: 20,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-084",
        _originalId: "product-084",
        _rev: "0eXuCLzlZROMt8M6TZo677",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:36Z",
        category: {
            _ref: "category-004",
            _type: "reference",
        },
        description:
            "Stylish leather boots with comfortable heel and durable sole",
        imageUrl:
            "https://images.pexels.com/photos/1356207/pexels-photo-1356207.jpeg",
        name: "Women's Boots 5",
        price: 99.99,
        slug: {
            _type: "slug",
            current: "womens-boots-5",
        },
        stock: 30,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-085",
        _originalId: "product-085",
        _rev: "mKqpFXcr0FhOVwpHKarCbi",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:37Z",
        category: {
            _ref: "category-005",
            _type: "reference",
        },
        description: "High-quality wireless earbuds with noise cancellation",
        imageUrl:
            "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb",
        name: "Wireless Earbuds 1",
        price: 149.99,
        slug: {
            _type: "slug",
            current: "wireless-earbuds-1",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-086",
        _originalId: "drafts.product-086",
        _rev: "e32aaf8e-94c4-4196-b1e0-fd94c80a95b9",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:38Z",
        category: {
            _ref: "category-006",
            _type: "reference",
        },
        description:
            "Versatile toaster oven for baking, toasting, and broiling",
        imageUrl:
            "https://images.pexels.com/photos/127846/pexels-photo-127846.jpeg",
        name: "Toaster Oven 1",
        price: 79.99,
        slug: {
            _type: "slug",
            current: "toaster-oven-1",
        },
        stock: 25,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-087",
        _originalId: "product-087",
        _rev: "mKqpFXcr0FhOVwpHKarEBh",
        _type: "product",
        _updatedAt: "2025-05-20T06:00:39Z",
        category: {
            _ref: "category-007",
            _type: "reference",
        },
        description: "Comprehensive cookbook with easy-to-follow recipes",
        imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f",
        name: "Cookbook 5",
        price: 49.99,
        slug: {
            _type: "slug",
            current: "cookbook-5",
        },
        stock: 40,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-088",
        _originalId: "product-088",
        _rev: "VVSFSz16PKgOOWeXMFhOBt",
        _type: "product",
        _updatedAt: "2025-05-20T05:49:53Z",
        category: {
            _ref: "category-008",
            _type: "reference",
        },
        description: "Soft and cuddly stuffed animal perfect for children",
        imageUrl:
            "https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg",
        name: "Stuffed Animal 5",
        price: 24.99,
        slug: {
            _type: "slug",
            current: "stuffed-animal-5",
        },
        stock: 50,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-089",
        _originalId: "product-089",
        _rev: "ZQ1DbMfh3J0S2TJo2hw3FG",
        _type: "product",
        _updatedAt: "2025-05-20T05:49:54Z",
        category: {
            _ref: "category-009",
            _type: "reference",
        },
        description: "High-quality exercise ball for yoga and fitness workouts",
        imageUrl:
            "https://images.pexels.com/photos/3825432/pexels-photo-3825432.jpeg",
        name: "Yoga Ball 5",
        price: 29.99,
        slug: {
            _type: "slug",
            current: "yoga-ball-5",
        },
        stock: 35,
    },
    {
        _createdAt: "2025-05-12T12:37:09Z",
        _id: "product-090",
        _originalId: "product-090",
        _rev: "0eXuCLzlZROMt8M6TZl5Qv",
        _type: "product",
        _updatedAt: "2025-05-20T05:49:55Z",
        category: {
            _ref: "category-010",
            _type: "reference",
        },
        description:
            "Elegant set of rings with unique designs and premium materials",
        imageUrl:
            "https://images.pexels.com/photos/1454122/pexels-photo-1454122.jpeg",
        name: "Ring Set 5",
        price: 99.99,
        slug: {
            _type: "slug",
            current: "ring-set-5",
        },
        stock: 20,
    },
];
