import { type Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Shopr',
    description: 'Generated by create next app',
}

export default function StudioLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true" >
                {children}
            </body>
        </html>
    )
}